import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { base44 } from "@/api/base44Client";
import { Globe, Shuffle, Sparkles, Volume2, RefreshCw } from "lucide-react";

const QUEENS_LANGUAGES = [
  { name: "Mandarin Chinese", community: "Flushing — the largest Chinatown outside Manhattan", emoji: "🇨🇳", script: "中文", fun_fact: "Flushing's Main Street is sometimes called 'the Times Square of Chinese America' — and the soup dumplings at Golden Mall's basement food court are a NYC bucket-list food." },
  { name: "Cantonese", community: "Flushing & Elmhurst — a distinct and vibrant Chinese dialect community", emoji: "🇨🇳", script: "廣東話", fun_fact: "Cantonese dim sum culture took root in Flushing in the 1980s; you can still find pushcart dim sum at old-school banquet halls on weekends — a disappearing NYC tradition." },
  { name: "Spanish", community: "Jackson Heights & Corona — one of NYC's largest Latino communities", emoji: "🇪🇸", script: "Español", fun_fact: "Jackson Heights was declared 'the most ethnically diverse urban area in the world' by the Guinness Book of World Records — a title it has held for decades." },
  { name: "Mexican Spanish", community: "Corona — one of the largest Mexican communities in NYC", emoji: "🇲🇽", script: "Español Mexicano", fun_fact: "Corona hosts one of NYC's most beloved Cinco de Mayo and Día de los Muertos celebrations — and Tortilleria Nixtamal in Corona makes fresh masa daily, drawing chefs from across the city." },
  { name: "Ecuadorian Spanish", community: "Jackson Heights & Corona — the largest Ecuadorian community in NYC", emoji: "🇪🇨", script: "Español Ecuatoriano", fun_fact: "Jackson Heights has the highest concentration of Ecuadorians outside Ecuador itself — their ceviche de concha (black clam ceviche) is a hidden Queens specialty." },
  { name: "Colombian Spanish", community: "Jackson Heights — a large Colombian community and cultural hub", emoji: "🇨🇴", script: "Español Colombiano", fun_fact: "Jackson Heights hosts an annual Colombian Independence Day parade — and the bakeries there sell some of the best pan de bono (cheese bread) and buñuelos in all of NYC." },
  { name: "Dominican Spanish", community: "Jamaica & Southeast Queens — vibrant Dominican community", emoji: "🇩🇴", script: "Español Dominicano", fun_fact: "Queens has produced several Dominican MLB stars — and Jamaica Avenue is packed with Dominican-owned restaurants serving la bandera (rice, beans & meat), the unofficial national plate." },
  { name: "Korean", community: "Flushing — Little Korea, one of the largest Korean communities outside Korea", emoji: "🇰🇷", script: "한국어", fun_fact: "Flushing's Korean scene features some of the most authentic Korean BBQ outside Seoul — the neighborhood even has a 24-hour Korean spa, Spa Castle, where you can eat bibimbap at 3am." },
  { name: "Hindi", community: "Jackson Heights & Elmhurst — the heart of South Asian Queens", emoji: "🇮🇳", script: "हिन्दी", fun_fact: "Jackson Heights' '74th Street Little India' corridor is famous for its Diwali lights, chaat stalls, and sari shops — Bollywood music fills the air on weekends and the pani puri is world-class." },
  { name: "Punjabi", community: "Richmond Hill — home to a thriving Sikh community", emoji: "🌐", script: "ਪੰਜਾਬੀ", fun_fact: "Richmond Hill's Sikh Cultural Society runs one of the largest Gurdwaras in NYC — free langar (communal meals open to anyone) are served daily, feeding thousands." },
  { name: "Gujarati", community: "Jackson Heights — alongside a thriving South Asian business district", emoji: "🌐", script: "ગુજરાતી", fun_fact: "Many of Jackson Heights' small businesses are Gujarati-owned — and the community celebrates Navratri with massive dandiya dance events drawing thousands of dancers to Queens ballrooms." },
  { name: "Bengali", community: "Jamaica — one of NYC's fastest-growing Bangladeshi communities", emoji: "🇧🇩", script: "বাংলা", fun_fact: "Jamaica's Bangladeshi community has spawned a mini food corridor on Hillside Avenue known for biryani, mishti doi (sweet yogurt), and roshogolla — Bengali sweets are an art form." },
  { name: "Urdu", community: "Jamaica & Richmond Hill — a major South Asian hub in southern Queens", emoji: "🇵🇰", script: "اردو", fun_fact: "Urdu poetry (sher-o-shayari) evenings are held in community halls in Jamaica — and the halal Pakistani food trucks on Jamaica Avenue are a beloved local institution serving nihari and haleem." },
  { name: "Tamil", community: "Jackson Heights & Flushing — South Indian Tamil community", emoji: "🌐", script: "தமிழ்", fun_fact: "The Ganesh Temple in Flushing — the largest Hindu temple in the US — has deep ties to the Tamil community. Devotees travel from across North America for festivals, and the temple's prasadam (blessed food) lines stretch around the block." },
  { name: "Telugu", community: "Flushing & Jamaica — South Indian Telugu-speaking professionals", emoji: "🌐", script: "తెలుగు", fun_fact: "Queens has a large Telugu-speaking IT professional community; the annual Ugadi (Telugu New Year) celebrations in Flushing feature Pachadi — a dish that blends six tastes symbolizing life's full spectrum." },
  { name: "Marathi", community: "Jackson Heights — part of the broader Maharashtrian diaspora", emoji: "🌐", script: "मराठी", fun_fact: "The Maharashtrian community in Queens celebrates Ganesh Chaturthi with outdoor processions — a 10-day festival that transforms the streets and features puran poli (sweet flatbread)." },
  { name: "Sinhalese", community: "Woodside & Elmhurst — Sri Lankan community", emoji: "🇱🇰", script: "සිංහල", fun_fact: "Elmhurst has Sri Lankan restaurants serving hoppers (bowl-shaped rice pancakes with eggs) and kottu roti — the percussive sound of kottu being chopped on the griddle is unmistakable and addictive." },
  { name: "Nepali", community: "Woodside & Jackson Heights — a growing Nepali community", emoji: "🇳🇵", script: "नेपाली", fun_fact: "The Nepali community brought momo dumplings to Queens — steamed or fried with spicy achar sauce, they are now a beloved Queens street food found far beyond the Nepali community." },
  { name: "Tibetan", community: "Jackson Heights — one of the largest Tibetan communities in the US", emoji: "🏔️", script: "བོད་སྐད", fun_fact: "Jackson Heights is home to 'Little Tibet' — the community center hosts Losar (Tibetan New Year) festivities and restaurants serve thenthuk (hand-pulled noodle soup) and butter tea alongside momos." },
  { name: "Greek", community: "Astoria — once the largest Greek community outside Greece", emoji: "🇬🇷", script: "Ελληνικά", fun_fact: "Astoria was once home to the largest Greek population outside of Greece — Steinway Street was dubbed 'Greek Broadway' and still has some of NYC's best baklava, spanakopita, and loukoumades (honey puffs)." },
  { name: "Arabic", community: "Astoria — home to a large Egyptian and Middle Eastern community", emoji: "🇪🇬", script: "عربي", fun_fact: "Astoria's Steinway Street is lined with Egyptian cafés, hookah lounges, and shawarma spots — the neighborhood's koshary (Egypt's beloved street-food rice dish) and Om Ali (bread pudding) are cult favorites." },
  { name: "Hebrew", community: "Forest Hills & Great Neck — Israeli expat and Jewish community", emoji: "🇮🇱", script: "עברית", fun_fact: "Forest Hills is home to the West Side Tennis Club, where the US Open was held until 1977 — the neighborhood also has Israeli cafés serving shakshuka and sabich (pita with fried eggplant) that rival Tel Aviv." },
  { name: "Yiddish", community: "Forest Hills — an Ashkenazi Jewish community with deep historical roots", emoji: "✡️", script: "ייִדיש", fun_fact: "Forest Hills sheltered many Holocaust survivors who rebuilt their lives in Queens — the neighborhood's Jewish delis and bakeries serving kugel, rugelach, and chopped liver are living tributes to that history." },
  { name: "Tagalog", community: "Woodside — 'Little Manila', one of the largest Filipino communities in the US", emoji: "🇵🇭", script: "Filipino", fun_fact: "Roosevelt Avenue in Woodside is the heart of Little Manila — Filipino bakeries sell ube (purple yam) cake and pandesal, and karaoke bars stay open until dawn. Filipino-Americans are one of Queens' most beloved communities." },
  { name: "Vietnamese", community: "Elmhurst & Woodside — a vibrant Vietnamese community", emoji: "🇻🇳", script: "Tiếng Việt", fun_fact: "Elmhurst has quietly become one of NYC's best spots for pho and banh mi — the Vietnamese community there also runs a bustling market on Broadway where ingredients unavailable elsewhere in NYC can be found." },
  { name: "Thai", community: "Elmhurst — home to Thai restaurants and a tight-knit Thai community", emoji: "🇹🇭", script: "ไทย", fun_fact: "A stretch of Woodside Avenue is informally called 'Thai Town' — it has some of NYC's most authentic Thai food, including boat noodles and som tam (green papaya salad) that food critics rave about." },
  { name: "Burmese", community: "Woodside & Elmhurst — a growing Southeast Asian community", emoji: "🇲🇲", script: "မြန်မာ", fun_fact: "Woodside has several Burmese restaurants serving mohinga (fish noodle soup) — considered Myanmar's national breakfast dish and a rare find outside Southeast Asia, drawing adventurous eaters from across NYC." },
  { name: "Khmer", community: "Elmhurst — Cambodian community rooted in Queens", emoji: "🇰🇭", script: "ខ្មែរ", fun_fact: "Elmhurst's Cambodian community survived the Khmer Rouge era and rebuilt here — their amok (coconut fish curry steamed in banana leaf) and num banh chok (rice noodles with green curry) are rare NYC delicacies." },
  { name: "Indonesian", community: "Elmhurst — one of the most diverse ZIP codes on Earth", emoji: "🇮🇩", script: "Bahasa Indonesia", fun_fact: "Elmhurst's ZIP code 11373 was declared the most ethnically diverse in the United States — Indonesian-style nasi goreng and rendang (slow-cooked coconut beef) can actually be found there, a rare NYC treat." },
  { name: "Japanese", community: "Flushing & Forest Hills — Japanese expats and professionals", emoji: "🇯🇵", script: "日本語", fun_fact: "Flushing has a growing cluster of Japanese ramen shops, izakayas, and convenience store-style delis — and the Queens Museum near Flushing Meadows (site of the 1939 and 1964 World's Fairs) has hosted major Japanese art exhibitions." },
  { name: "Romanian", community: "Sunnyside & Woodside — a large Eastern European community", emoji: "🇷🇴", script: "Română", fun_fact: "Sunnyside has a Romanian Orthodox church and several Eastern European bakeries — and the community is known for celebrating Orthodox Easter with midnight candlelit processions and cozonac (sweet braided bread)." },
  { name: "Polish", community: "Ridgewood — historically Polish neighborhood on the Queens/Brooklyn border", emoji: "🇵🇱", script: "Polski", fun_fact: "Ridgewood still has Polish butcher shops, delis, and a beloved kielbasa tradition — and the neighborhood's historic Mathews Model Flats row houses are on the National Register of Historic Places." },
  { name: "Russian", community: "Forest Hills & Rego Park — a major Russian-speaking Jewish community", emoji: "🇷🇺", script: "Русский", fun_fact: "Rego Park's 'Little Moscow' on Queens Blvd has Russian bookstores, delis, and restaurants serving borscht and pelmeni — and the local Russian Jewish community has produced several prominent NYC politicians." },
  { name: "Ukrainian", community: "Sunnyside & Woodside — a growing Ukrainian community", emoji: "🇺🇦", script: "Українська", fun_fact: "Since 2022, Queens has welcomed a surge of Ukrainian refugees; the community organizes fundraisers at Ukrainian social halls in Sunnyside that date back to the 1950s, now more vital than ever." },
  { name: "Uzbek", community: "Rego Park — a large Bukharian Jewish community from Central Asia", emoji: "🇺🇿", script: "O'zbek", fun_fact: "Rego Park's Bukharian corridor on 108th Street has Uzbek restaurants serving plov (rice pilaf with lamb and carrots) and samsa pastries — one of the most unique food scenes in all of NYC." },
  { name: "Hungarian", community: "Woodside & Sunnyside — Eastern European Hungarian community", emoji: "🇭🇺", script: "Magyar", fun_fact: "Queens' Hungarian community was bolstered by refugees after the 1956 Budapest uprising — a chapter of history commemorated at Hungarian cultural events featuring goulash and lángos (fried dough) in Woodside." },
  { name: "Albanian", community: "Astoria & Woodside — one of the largest Albanian communities in the US", emoji: "🇦🇱", script: "Shqip", fun_fact: "Astoria has one of the largest Albanian populations in the Western Hemisphere — the community runs Albanian-language schools, celebrates Albanian Independence Day with a parade, and makes qofte (grilled meatballs) at community cookouts." },
  { name: "Serbian", community: "Astoria — home to a vibrant Serbian Orthodox community", emoji: "🇷🇸", script: "Српски", fun_fact: "Astoria's St. Sava Serbian Orthodox Church is a Queens landmark — the community celebrates Slava (patron saint's day) with feasts of pogaca bread, roast pork, and homemade rakija (fruit brandy)." },
  { name: "Croatian", community: "Astoria — part of the South Slavic diaspora in western Queens", emoji: "🇭🇷", script: "Hrvatski", fun_fact: "The Croatian community in Astoria has deep roots going back to post-WWII immigration waves — the Croatian Catholic parish there has served the community for decades, hosting events with peka (slow-cooked meat under embers)." },
  { name: "Turkish", community: "Sunnyside & Astoria — a Turkish community with cultural presence", emoji: "🇹🇷", script: "Türkçe", fun_fact: "Sunnyside has Turkish restaurants and baklava shops that rival Istanbul — and the Turkish bath (hammam) tradition lives on at several Astoria spas where regulars gather for steam and kese (exfoliating scrub)." },
  { name: "French", community: "Astoria & Jamaica — Francophone West African and Caribbean communities", emoji: "🇫🇷", script: "Français", fun_fact: "Queens has Francophone West African communities in Jamaica where French-language churches serve as anchors — and thieboudienne (Senegalese rice and fish, considered West Africa's most iconic dish) is a local staple." },
  { name: "Italian", community: "Howard Beach & Ozone Park — Italian-American heritage neighborhoods", emoji: "🇮🇹", script: "Italiano", fun_fact: "Howard Beach is famously Italian-American — it's home to the original Gino's Focacceria (founded 1904, one of NYC's oldest restaurants) and was the setting for parts of the film Saturday Night Fever." },
  { name: "Portuguese", community: "Astoria & Sunnyside — Brazilian and Portuguese communities", emoji: "🇧🇷", script: "Português", fun_fact: "Astoria has a growing Brazilian community with churrascarias and pão de queijo shops — and the annual Brazilian Day celebration draws thousands to dance samba and eat coxinha (fried chicken croquettes)." },
  { name: "Haitian Creole", community: "Cambria Heights — a large Haitian community in southeastern Queens", emoji: "🇭🇹", script: "Kreyòl", fun_fact: "Cambria Heights has one of the highest concentrations of Haitian-Americans in NYC — the community is celebrated for griot (fried pork) and soup joumou (pumpkin soup), which Haitians eat every January 1st to commemorate freedom." },
  { name: "Jamaican Patois", community: "Jamaica & Southeast Queens — one of the largest Jamaican communities outside the Caribbean", emoji: "🇯🇲", script: "Patwa", fun_fact: "Jamaica, Queens — the neighborhood — actually got its name from the Jameco Native Americans, not the Caribbean island. Yet the borough now has one of the largest Jamaican diasporas outside Jamaica, with jerk chicken spots on every block." },
  { name: "Trinidadian Creole", community: "Southeast Queens — large Trinidadian-American community", emoji: "🇹🇹", script: "Trini", fun_fact: "Southeast Queens hosts massive Carnival celebrations inspired by Trinidad's Mardi Gras tradition — doubles (curried chickpea on bara bread, eaten as street breakfast) are a beloved Queens street food from this community." },
  { name: "Guyanese Creole", community: "Richmond Hill — the largest Guyanese community outside Guyana", emoji: "🇬🇾", script: "Guyanese", fun_fact: "Richmond Hill's 'Little Guyana' on Liberty Avenue is the largest Guyanese community outside Guyana itself — pholourie (fried dough balls with tamarind chutney) and roti shops line the avenue, open late into the night." },
  { name: "Amharic", community: "Jamaica & Southeast Queens — a growing East African community", emoji: "🇪🇹", script: "አማርኛ", fun_fact: "Queens' Ethiopian community runs injera restaurants where you eat communally from one large platter — a tradition of togetherness (called gursha, feeding someone by hand) that has introduced thousands of New Yorkers to East African culture." },
  { name: "Tigrinya", community: "Jamaica — Eritrean community in southeastern Queens", emoji: "🇪🇷", script: "ትግርኛ", fun_fact: "Queens' Eritrean community celebrates Eritrean Independence Day (May 24) with street gatherings — their zigni (spicy beef stew) and shiro (chickpea paste with berbere spice) are staples at community dinners that draw neighbors of all backgrounds." },
  { name: "Somali", community: "Jamaica — Somali immigrant community in southeastern Queens", emoji: "🇸🇴", script: "Soomaali", fun_fact: "Jamaica's Somali community runs tea houses serving suqaar (spiced diced meat) and anjero flatbread — Somali tea spiced with cardamom, cinnamon, and cloves is a cultural institution and social ritual." },
  { name: "Wolof", community: "Southeast Queens — West African Senegalese community", emoji: "🇸🇳", script: "Wolof", fun_fact: "The Senegalese community in Southeast Queens hosts weekly wrestling viewing parties — laamb (Senegalese wrestling) is the national sport, and thieboudienne (the national dish of Senegal) is considered their greatest gift to Queens' dining scene." },
  { name: "Yoruba", community: "Jamaica & Southeast Queens — Nigerian Yoruba community", emoji: "🇳🇬", script: "Yorùbá", fun_fact: "The Yoruba community in Queens celebrates egungun masquerade festivals and runs Nigerian churches — jollof rice debates between Nigerian communities are fierce, and Queens has some of the best jollof outside Lagos." },
  { name: "Igbo", community: "Southeast Queens — Nigerian Igbo community", emoji: "🇳🇬", script: "Igbo", fun_fact: "The Igbo community in Southeast Queens is known for strong professional networks and rotating credit societies (esusu) — their ofe onugbu (bitter leaf soup) and nkwobi (spiced cow foot) are hidden Queens restaurant specialties." },
  { name: "Twi", community: "Southeast Queens — Ghanaian Akan community", emoji: "🇬🇭", script: "Twi", fun_fact: "Ghanaians in Southeast Queens run fufu restaurants where dishes are pounded fresh daily — Ghana's groundnut soup with fufu is a soul-warming staple, and Ghanaian waakye (rice and beans) is considered one of West Africa's greatest street foods." },
  { name: "Swahili", community: "Southeast Queens — East African diaspora community", emoji: "🌍", script: "Kiswahili", fun_fact: "The East African community in Queens spans Kenyans, Tanzanians, and Ugandans — their sukuma wiki (collard greens sautéed with tomato) and ugali (cornmeal porridge eaten by hand) have quietly appeared at Queens markets." },
  { name: "Fulani", community: "Southeast Queens — West African Fulani community", emoji: "🌍", script: "Fulfulde", fun_fact: "The Fula (Fulani) diaspora in Queens spans multiple West African nations — traditionally nomadic cattle herders, in Queens they have built merchant and business networks and celebrate their culture with elaborate silver jewelry traditions." },
  { name: "Persian (Farsi)", community: "Forest Hills & Rego Park — Iranian Jewish and Muslim communities", emoji: "🇮🇷", script: "فارسی", fun_fact: "Rego Park has Persian Jewish restaurants and bakeries serving shirini (pastries) and kabob — the Iranian community's fesenjan (pomegranate and walnut stew) and ghormeh sabzi are among NYC's most aromatic hidden culinary gems." },
  { name: "Pashto", community: "Flushing & Jamaica — Afghan community in Queens", emoji: "🇦🇫", script: "پښتو", fun_fact: "Queens has one of the largest Afghan communities on the East Coast — Afghan kebab restaurants and tandoor naan bakeries in Flushing are beloved across the borough, and mantu (steamed dumplings with yogurt) are a Queens sleeper hit." },
  { name: "Dari", community: "Flushing — Afghan Dari-speaking community", emoji: "🇦🇫", script: "دری", fun_fact: "Dari-speaking Afghans in Flushing run acclaimed restaurants serving qabili palau (rice with lamb, carrots, and raisins) — considered the national dish of Afghanistan and one of the world's great rice dishes." },
  { name: "Bukharian", community: "Rego Park & Forest Hills — the largest Bukharian Jewish community outside Central Asia", emoji: "🕍", script: "Бухорӣ", fun_fact: "Rego Park's 108th Street is the heart of Bukharian Jewish culture in America — their osh palov (rice with lamb and vegetables, eaten at lifecycle events) is considered one of Queens' most underrated culinary treasures." },
  { name: "Czech", community: "Astoria — Central European community", emoji: "🇨🇿", script: "Čeština", fun_fact: "Czech immigration to Queens peaked after WWII and again after 1968 — the community has held annual gatherings celebrating Masopust (Czech Mardi Gras) with kolache pastries, svíčková (braised beef), and pilsner beer." },
  { name: "Slovak", community: "Woodside — Slovak immigrant community", emoji: "🇸🇰", script: "Slovenčina", fun_fact: "Slovak immigrants helped build Woodside's strong Central European identity — traditional bryndza halusky (potato dumplings with sheep cheese and bacon) and kapustnica (sauerkraut soup) appear at community gatherings." },
  { name: "Malay", community: "Elmhurst — Southeast Asian Malaysian community", emoji: "🇲🇾", script: "Bahasa Melayu", fun_fact: "Elmhurst has a handful of Malaysian restaurants serving laksa (spicy coconut noodle soup) and nasi lemak (coconut rice with sambal) — a rare find in NYC that draws food-obsessed New Yorkers from across the boroughs." },
  { name: "Cebuano", community: "Woodside — Visayan Filipino community alongside Little Manila", emoji: "🇵🇭", script: "Bisaya", fun_fact: "Cebuano speakers from the Visayas region are well-represented in Woodside's Little Manila — lechon from Cebu is considered the finest whole roast pig in the Philippines, and Cebuano celebrations in Queens are legendary for the food spread." },
  { name: "Ilocano", community: "Woodside — Northern Filipino community in Little Manila", emoji: "🇵🇭", script: "Ilokano", fun_fact: "Ilocanos from Northern Luzon are a major part of Woodside's Filipino community — their bagnet (crispy fried pork belly) and pinakbet (bitter melon and shrimp paste vegetable stew) are Filipino classics found in Little Manila." },
  { name: "Kapampangan", community: "Woodside — Pampanga Filipino community", emoji: "🇵🇭", script: "Kapampangan", fun_fact: "Kapampangans from Pampanga province are considered the culinary masters of the Philippines — their sisig (sizzling chopped pork cheeks with egg and calamansi) has become one of the hottest Filipino dishes in NYC food culture." },
  { name: "Punjabi (Pakistani)", community: "Jamaica & Richmond Hill — Pakistani Punjabi community", emoji: "🇵🇰", script: "پنجابی", fun_fact: "Jamaica Avenue has a stretch of Pakistani Punjabi-owned halal restaurants and sweet shops — their nihari (slow-cooked beef shank stew) is a beloved Sunday morning tradition, and the mithai (sweets) are some of the best in NYC." },
  { name: "Sindhi", community: "Jackson Heights — Sindhi Hindu and Muslim diaspora", emoji: "🇵🇰", script: "سنڌي", fun_fact: "The Sindhi community — many of whom fled Partition in 1947 — are known as global traders; their sai bhaji (Sindhi spinach and vegetable dish) and koki (spiced flatbread) are comfort food staples at community gatherings in Queens." },
  { name: "Balochi", community: "Jamaica — small but tight-knit Balochi community", emoji: "🌐", script: "بلوچی", fun_fact: "Balochi speakers in Queens come from Pakistan's largest province (44% of Pakistan's land area) — their sajji (whole marinated lamb slow-roasted over coals) is a delicacy rarely found outside South Asian specialty restaurants." },
  { name: "Kashmiri", community: "Jackson Heights — Kashmiri diaspora in South Asian corridor", emoji: "🌐", script: "کٲشُر", fun_fact: "The Kashmiri community in Queens is known for noon chai (pink salty tea with cardamom and almonds) and rogan josh (slow-cooked lamb in aromatic spices) — their wazwan multi-course feast tradition is considered one of South Asia's greatest culinary events." },
  { name: "Oriya (Odia)", community: "Flushing & Jackson Heights — Odisha diaspora community", emoji: "🌐", script: "ଓଡ଼ିଆ", fun_fact: "The Odia community celebrates Rath Yatra (chariot festival) with processions — one of the most colorful Hindu festivals in Queens, drawing crowds from across the tristate area. Their chhena poda (burnt cheese dessert) is considered Odisha's greatest culinary contribution." },
  { name: "Malayalam", community: "Flushing & Jackson Heights — Kerala community, one of the most educated immigrant groups", emoji: "🌐", script: "മലയാളം", fun_fact: "Kerala's large Christian, Muslim, and Hindu communities are all represented in Queens — their sadya (a 26-dish banana leaf feast served during Onam) is a masterclass in vegetarian cooking and the most elaborate meal in South Asian cuisine." },
  { name: "Kannada", community: "Flushing — Karnataka community of IT professionals and students", emoji: "🌐", script: "ಕನ್ನಡ", fun_fact: "Karnataka's contribution to Queens includes a strong IT professional community — and their bisi bele bath (spiced rice and lentil dish with ghee) and filter coffee culture (served in a traditional tumbler) are gaining NYC fans." },
  { name: "Assamese", community: "Jackson Heights — small Northeast Indian diaspora", emoji: "🌐", script: "অসমীয়া", fun_fact: "Assamese speakers in Queens hail from one of India's most biodiverse regions — their bihu dance (celebrating the Assamese New Year in April) is performed at community events in Jackson Heights, and pitha (rice cakes) are made for the occasion." },
  { name: "Dzongkha", community: "Woodside — Bhutanese refugee community", emoji: "🇧🇹", script: "རྫོང་ཁ", fun_fact: "Bhutan is the only carbon-negative country in the world and measures Gross National Happiness — Woodside's Bhutanese refugee community (many resettled from Nepali camps over 15+ years) brings that philosophy of collective well-being to Queens." },
  { name: "Mongolian", community: "Flushing — a growing Mongolian community near Little Asia", emoji: "🇲🇳", script: "Монгол", fun_fact: "Flushing has Mongolian restaurants serving buuz (steamed dumplings) and tsuivan (hand-pulled noodles with meat) — the community also holds Naadam festival events celebrating wrestling, archery, and horse racing, the three 'manly sports' of Mongolia." },
  { name: "Uyghur", community: "Flushing — Central Asian Uyghur diaspora community", emoji: "🌐", script: "ئۇيغۇرچە", fun_fact: "Flushing has Uyghur restaurants serving laghman (hand-pulled noodles with stir-fried vegetables) and samsa (baked lamb pastries) — the food draws long lines of adventurous NYC eaters and has introduced many to Central Asian cuisine." },
  { name: "Kazakh", community: "Rego Park — Central Asian community near Bukharian corridor", emoji: "🇰🇿", script: "Қазақша", fun_fact: "Kazakhstan is the world's largest landlocked country — the Kazakh community in Rego Park bridges Central Asian and Russian-speaking cultures, gathering around beshbarmak (boiled meat with flat noodles, eaten by hand from a communal platter)." },
  { name: "Kyrgyz", community: "Rego Park — small Central Asian community", emoji: "🇰🇬", script: "Кыргызча", fun_fact: "The Kyrgyz community in Queens is small but connected to the larger Central Asian network in Rego Park — their manti (steamed dumplings with pumpkin or lamb) and kumis (fermented mare's milk) are Central Asian cultural touchstones." },
  { name: "Tajik", community: "Rego Park & Flushing — Tajik diaspora community", emoji: "🇹🇯", script: "Тоҷикӣ", fun_fact: "Tajikistan has more mountains than any other Central Asian country, with 93% of its terrain mountainous — the Tajik community in Queens is known for qurutob (flatbread soaked in sour cream with vegetables, considered Tajikistan's national dish)." },
  { name: "Azerbaijani", community: "Forest Hills — Azerbaijani community, often overlapping with Bukharian Jewish networks", emoji: "🇦🇿", script: "Azərbaycan", fun_fact: "Azerbaijan sits at the crossroads of Europe and Asia and is the birthplace of fire worshipping (the 'Land of Fire') — the Azerbaijani community in Forest Hills holds Novruz (New Year) celebrations featuring bonfires, dolma, and plov." },
  { name: "Armenian", community: "Forest Hills & Rego Park — Armenian community with roots in the Middle East", emoji: "🇦🇲", script: "Հայերեն", fun_fact: "Queens' Armenian community, many descended from genocide survivors, has built churches and cultural centers — Armenian lahmajun (thin flatbread with spiced meat, called 'Armenian pizza') is a beloved community specialty." },
  { name: "Georgian", community: "Forest Hills — Georgian Jewish and Christian communities", emoji: "🇬🇪", script: "ქართული", fun_fact: "Georgian cuisine is Queens' most underrated hidden gem — khachapuri (cheese-filled bread boat topped with a poached egg and butter) and khinkali (soup dumplings twisted with 21 pleats) are served at Forest Hills Georgian restaurants." },
  { name: "Macedonian", community: "Astoria — part of the South Slavic community in western Queens", emoji: "🇲🇰", script: "Македонски", fun_fact: "The Macedonian community in Astoria has a cultural center and Orthodox church — their tavce gravce (slow-baked white bean casserole, considered the national dish) and turlitava (vegetable and meat stew) are warming community dinner staples." },
  { name: "Bulgarian", community: "Astoria & Woodside — Eastern European Bulgarian community", emoji: "🇧🇬", script: "Български", fun_fact: "Bulgaria is home to the world's oldest confirmed gold artifacts (6,000 years old) — Queens' Bulgarian community celebrates Baba Marta (March 1) by exchanging martenitsi (red-and-white yarn tassels) for health and good luck." },
  { name: "Slovenian", community: "Astoria — small Slovenian community in western Queens", emoji: "🇸🇮", script: "Slovenščina", fun_fact: "Slovenia was the first Yugoslav republic to declare independence in 1991 — the small Slovenian community in Astoria keeps traditions of potica (walnut-filled roll pastry, baked for every holiday) alive at cultural events." },
  { name: "Bosnian", community: "Astoria & Ridgewood — Bosnian Muslim community", emoji: "🇧🇦", script: "Bosanski", fun_fact: "Many Bosnians arrived in Queens as refugees from the 1990s war — they brought ćevapi (grilled minced meat sausages with kajmak cream cheese) and burek (flaky phyllo pastry with meat or cheese), adding to Astoria's already extraordinary food mosaic." },
  { name: "Maltese", community: "Astoria — historic Maltese community", emoji: "🇲🇹", script: "Malti", fun_fact: "Malta is Europe's smallest nation and Maltese is the only Semitic language written in the Latin alphabet — Astoria's historic Maltese community, established in the mid-20th century, celebrates feasts with pastizzi (flaky cheese pastries)." },
  { name: "Catalan", community: "Astoria — Spanish and Catalan expat community", emoji: "🌐", script: "Català", fun_fact: "Catalan has survived centuries of suppression to remain a living language spoken by 10 million people — Queens has a small but proud Catalan community that celebrates the Diada de Catalunya (Catalan National Day) each September 11th." },
  { name: "Galician", community: "Astoria — Galician Spanish community", emoji: "🌐", script: "Galego", fun_fact: "Galicia in northwest Spain has its own Celtic cultural heritage, including bagpipes (gaita galega) — the Galician community in Astoria keeps this music alive alongside pulpo a la gallega (octopus with paprika and olive oil) at community feasts." },
  { name: "Basque", community: "Astoria — small Basque community in western Queens", emoji: "🌐", script: "Euskara", fun_fact: "Basque is a language isolate — it shares no known relatives with any other language in the world, a 10,000-year-old mystery. The Basque community in Queens gathers for pelota (handball) and pintxos (tapas) evenings." },
  { name: "Dutch", community: "Astoria & Long Island City — Dutch expat and heritage community", emoji: "🇳🇱", script: "Nederlands", fun_fact: "Queens itself was shaped by Dutch colonial history — Flushing's name derives from the Dutch city Vlissingen, and the 1657 Flushing Remonstrance (signed there) was America's first legal defense of religious freedom, predating the Constitution by 132 years." },
  { name: "Swedish", community: "Astoria — Scandinavian expat community", emoji: "🇸🇪", script: "Svenska", fun_fact: "ABBA, Ingmar Bergman, and IKEA are Sweden's most famous cultural exports — Astoria's Scandinavian community celebrates midsommar with flower crowns, herring, and snaps, a charmingly incongruous Queens tradition." },
  { name: "Norwegian", community: "Astoria — historic Scandinavian community in western Queens", emoji: "🇳🇴", script: "Norsk", fun_fact: "Astoria once had a significant Norwegian seafarer community given its waterfront location on the East River — the area around Astoria Park still has vestiges of Nordic social clubs, and Norway's lefse (potato flatbread) appears at heritage events." },
  { name: "Finnish", community: "Astoria — small Northern European community", emoji: "🇫🇮", script: "Suomi", fun_fact: "Finland invented the concept of the sauna — a fitting heritage for the Finnish community in Astoria, where hammam-style bathhouses carry on that communal bathing tradition. Finland also has the most coffee drinkers per capita in the world." },
  { name: "Danish", community: "Astoria — Scandinavian expat and heritage community", emoji: "🇩🇰", script: "Dansk", fun_fact: "Denmark gave the world hygge (cozy contentment) — Astoria's Danish expat community has brought that aesthetic to the borough, gathering in cafés over smørrebrød (open-faced sandwiches) and Danish pastries (which Danes actually call Viennese bread)." },
  { name: "Afrikaans", community: "Southeast Queens — South African expat community", emoji: "🇿🇦", script: "Afrikaans", fun_fact: "Afrikaans developed in the Cape Colony from 17th-century Dutch and became its own language by the 1800s — South African expats in Queens often gather to watch rugby matches and braai (barbecue) in backyards, a deeply social tradition." },
  { name: "Zulu", community: "Southeast Queens — South African Zulu diaspora", emoji: "🇿🇦", script: "isiZulu", fun_fact: "Zulu is the most widely spoken language in South Africa — the Zulu community in Queens keeps the tradition of isicathamiya (the a cappella music made famous by Ladysmith Black Mambazo and Paul Simon's Graceland) alive in community performances." },
  { name: "Xhosa", community: "Southeast Queens — South African Xhosa diaspora", emoji: "🇿🇦", script: "isiXhosa", fun_fact: "Xhosa is famous for its click consonants (three distinct types) — Nelson Mandela was Xhosa, and Xhosa's musical quality has inspired pop stars worldwide, including Beyoncé's use of the language in her music." },
  { name: "Shona", community: "Southeast Queens — Zimbabwean community", emoji: "🇿🇼", script: "ChiShona", fun_fact: "The Shona people of Zimbabwe are world-renowned for their mbira (thumb piano) music — Queens' Zimbabwean community has introduced this hauntingly beautiful UNESCO-recognized instrument to NYC audiences at cultural events." },
  { name: "Lingala", community: "Southeast Queens — Congolese community", emoji: "🇨🇩", script: "Lingála", fun_fact: "Lingala is the language of Congolese music legends Papa Wemba and Fally Ipupa — Southeast Queens' Congolese community keeps soukous (electric guitar-driven dance music born in Kinshasa) alive in local venues and community halls." },
  { name: "Kikuyu", community: "Jamaica — Kenyan Kikuyu community", emoji: "🇰🇪", script: "Gĩkũyũ", fun_fact: "The Kikuyu are Kenya's largest ethnic group, and Barack Obama's Kenyan family traces some heritage to this region — Queens' Kenyan community holds long-distance running groups (Kenya dominates global marathon records) and nyama choma (roasted meat) cookouts." },
  { name: "Oromo", community: "Jamaica — Ethiopian and East African Oromo diaspora", emoji: "🇪🇹", script: "Afaan Oromoo", fun_fact: "The Oromo are Ethiopia's largest ethnic group and produce world-class long-distance runners — Feyisa Lilesa, who raised clasped hands in protest at the 2016 Rio Olympics, is an Oromo icon celebrated by Queens' community." },
  { name: "Tigre", community: "Jamaica — Eritrean Tigre-speaking community", emoji: "🇪🇷", script: "ትግሬ", fun_fact: "Tigre-speaking Eritreans in Queens often gather in coffee ceremony circles (bun tetu) — the Eritrean coffee ritual involves roasting beans fresh in front of guests, wafting frankincense smoke, and serving three rounds of coffee. A Queens neighbor's dream invitation." },
  { name: "Dinka", community: "Jamaica — South Sudanese Dinka community", emoji: "🇸🇸", script: "Thuɔŋjäŋ", fun_fact: "The Dinka are among the world's tallest people on average — many South Sudanese Nuer and Dinka in Queens are former 'Lost Boys,' whose stories of walking hundreds of miles across Sudan to survive are among the most extraordinary in recent history." },
  { name: "Hausa", community: "Southeast Queens — West African Hausa community from Nigeria and Niger", emoji: "🇳🇬", script: "Hausa", fun_fact: "Hausa is West Africa's most widely spoken language with 80 million speakers — the community in Southeast Queens runs suya (spiced beef skewer) stands and kuli-kuli (peanut snack) shops that are hidden culinary gems for Queens food explorers." },
  { name: "Mandinka", community: "Southeast Queens — Gambian and Senegalese Mandinka community", emoji: "🇬🇲", script: "Mandinka", fun_fact: "Alex Haley's Roots traced his ancestry to a Mandinka griot (oral historian) named Kunta Kinte in The Gambia — the Mandinka community in Queens keeps this oral storytelling and kora (21-string harp-lute) music tradition vibrantly alive." },
  { name: "Krio", community: "Southeast Queens — Sierra Leonean Krio-speaking community", emoji: "🇸🇱", script: "Krio", fun_fact: "Krio emerged from freed enslaved Africans who settled in Freetown, Sierra Leone, in the 1790s — their descendants created a unique culture and language. Queens' Sierra Leonean community blends West African and American traditions in a distinctive Queens way." },
  { name: "Fula Jallon", community: "Southeast Queens — Guinean Fula community", emoji: "🇬🇳", script: "Pular", fun_fact: "The Fula (Fulani) of Guinea are historically a nomadic pastoralist people known for intricate silver jewelry and elaborate braided hairstyles — the community in Queens runs trade networks spanning multiple countries and continents." },
  { name: "Bambara", community: "Southeast Queens — Malian Bambara community", emoji: "🇲🇱", script: "Bamanankan", fun_fact: "Mali was home to Timbuktu — a medieval center of Islamic scholarship with 700,000 manuscripts — the Bambara community in Queens hosts concerts featuring the kora and djembe drum, bringing West African musical heritage to NYC." },
  { name: "Ewe", community: "Southeast Queens — Ghanaian and Togolese Ewe community", emoji: "🇬🇭", script: "Eʋegbe", fun_fact: "The Ewe are renowned for their intricate kente cloth weaving (each pattern tells a story) — Ewe-speaking weavers in Southeast Queens have brought this UNESCO-recognized textile art to NYC markets and gallery shows." },
  { name: "Ga", community: "Southeast Queens — Ghanaian Ga-speaking community from Accra", emoji: "🇬🇭", script: "Gã", fun_fact: "The Ga people of Accra are famous for their fantasy coffins (shaped like Mercedes cars, fish, or eagles) that celebrate a person's life — and their kenkey (sour fermented corn dumpling) with whole fried fish and pepper sauce is a community gathering staple in Queens." },
  { name: "Bassa", community: "Southeast Queens — Liberian Bassa community", emoji: "🇱🇷", script: "Bassa", fun_fact: "The Bassa are one of Liberia's largest ethnic groups — the Liberian community in Southeast Queens holds events commemorating Liberian Independence Day (July 26, Africa's first republic) with fufu, palm butter soup, and lapa fabric fashion." },
  { name: "Kreyòl Ayisyen (rural)", community: "Cambria Heights — Haitian community from various regional dialects", emoji: "🇭🇹", script: "Kreyòl", fun_fact: "Haiti was the first Black republic in the world after its 1804 revolution — Cambria Heights celebrates Haitian Flag Day (May 18) as a proud community event with soup joumou (pumpkin soup of freedom, eaten only since slavery ended)." },
  { name: "Martinican Creole", community: "Southeast Queens — French Caribbean Martinican community", emoji: "🇲🇶", script: "Kréyòl", fun_fact: "Martinique is the birthplace of Aimé Césaire, the poet who coined 'Négritude' and influenced global postcolonial thought — the community in Queens holds literary evenings celebrating Caribbean French intellectual traditions alongside acras de morue (salt cod fritters)." },
  { name: "Guadeloupean Creole", community: "Southeast Queens — French Caribbean community", emoji: "🇬🇵", script: "Kréyòl", fun_fact: "Guadeloupe is shaped like a butterfly from the air, with two distinct islands — their bokit (fried bread sandwiches) and accras de morue (salt cod fritters) are beloved island snacks found at Southeast Queens Guadeloupean community gatherings." },
  { name: "Barbadian Creole", community: "Southeast Queens — Bajan community", emoji: "🇧🇧", script: "Bajan", fun_fact: "Rihanna is Barbados' most famous global ambassador — and Bajan cou-cou (cornmeal and okra, the national dish) with flying fish is proudly served at Southeast Queens' Bajan community gatherings, often preceded by a Banks beer." },
  { name: "Grenadian Creole", community: "Southeast Queens — Grenadian community", emoji: "🇬🇩", script: "Creole", fun_fact: "Grenada is known as the 'Spice Isle' — it produces 20% of the world's nutmeg, along with mace, cinnamon, and cloves. Oil down (breadfruit and callaloo stew, the national dish) is the star of Grenadian community cookouts in Queens." },
  { name: "Vincentian Creole", community: "Southeast Queens — St. Vincent and the Grenadines community", emoji: "🇻🇨", script: "Creole", fun_fact: "St. Vincent is one of the few places where Garifuna (Afro-Caribbean indigenous) culture survives — roasted breadfruit and fried jackfish are Vincentian community favorites in Southeast Queens, and Vincy Mas (Carnival) celebrations are exuberant." },
  { name: "Belizean Creole", community: "Southeast Queens — Belizean community", emoji: "🇧🇿", script: "Kriol", fun_fact: "Belize is home to the second largest barrier reef in the world and some of the most intact ancient Maya ruins — the Belizean community in Queens is known for rice and beans (cooked in coconut milk) and stew chicken, comfort food of the first order." },
  { name: "Papiamento", community: "Southeast Queens — Aruban and Curaçaoan community", emoji: "🇦🇼", script: "Papiamentu", fun_fact: "Papiamento is one of the few Creole languages to achieve official status — Aruba and Curaçao's community in Queens is known for their liveliness, Carnival traditions, and keshi yena (a whole Gouda cheese stuffed with spiced meat, one of the most dramatic dishes in the Caribbean)." },
  { name: "Sranan Tongo", community: "Southeast Queens — Surinamese community", emoji: "🇸🇷", script: "Sranan", fun_fact: "Suriname is South America's only Dutch-speaking country and one of its most diverse — the Surinamese community in Queens is celebrated for pom (cassava and chicken casserole with citrus, brought by Jewish Surinamese immigrants) and roti with chicken curry." },
  { name: "Paraguayan Guaraní", community: "Jackson Heights — Paraguayan community in Little South America", emoji: "🇵🇾", script: "Avañe'ẽ", fun_fact: "Paraguay is the only country where Guaraní (an indigenous language) is co-official alongside Spanish and spoken by most of the population — the community in Jackson Heights prepares sopa paraguaya (cornbread with cheese and onion, despite its name it's actually solid food)." },
  { name: "Quechua", community: "Jackson Heights & Corona — indigenous Peruvian and Ecuadorian communities", emoji: "🌎", script: "Runa Simi", fun_fact: "Quechua was the language of the Inca Empire, the largest empire in pre-Columbian America — the community in Jackson Heights preserves it through music and festivals, and their ceviche (Peru's national dish) and lomo saltado are Queens culinary institutions." },
  { name: "Aymara", community: "Jackson Heights — Bolivian indigenous diaspora", emoji: "🇧🇴", script: "Aymar aru", fun_fact: "Aymara is spoken around Lake Titicaca, the world's highest navigable lake at 12,500 feet — the Bolivian community in Jackson Heights celebrates Inti Raymi (Sun Festival) and serves salteñas (baked empanadas with broth inside, a technique so precise they're called Bolivia's greatest culinary achievement)." },
  { name: "Nahuatl", community: "Corona & Flushing — Mexican indigenous community", emoji: "🇲🇽", script: "Nāhuatl", fun_fact: "Nahuatl gave English the words chocolate, tomato, avocado, chili, and hundreds more — the Nahuatl-speaking community in Corona carries on this culinary legacy with tamales and mole negro (requires over 30 ingredients and days of preparation) that are among the best in NYC." },
  { name: "Mixtec", community: "Corona — one of the largest Mixtec communities outside Oaxaca", emoji: "🇲🇽", script: "Ñuu Savi", fun_fact: "Corona has the largest Mixtec community outside Oaxaca — they are key workers in NYC's restaurant industry, and their tlayudas (large crispy tortilla with black beans and meat) and mezcal (smoky agave spirit) are Oaxacan food culture at its most authentic." },
  { name: "Zapotec", community: "Jackson Heights — Oaxacan Zapotec community", emoji: "🇲🇽", script: "Didxazá", fun_fact: "The Zapotecs built Monte Albán, one of Mesoamerica's oldest cities, in 500 BC — the Zapotec community in Jackson Heights preserves their language and serves tlayudas and chapulines (toasted grasshoppers with chili and lime, a 2,000-year-old Oaxacan snack) at market stalls." },
  { name: "Mayan (Yucatec)", community: "Jackson Heights & Corona — Yucatán Maya community", emoji: "🇲🇽", script: "Màaya T'àan", fun_fact: "The Maya calendar famously 'ended' in 2012 — it didn't, and neither did Maya culture: the community in Queens serves cochinita pibil (slow-roasted pork marinated in annatto and citrus, wrapped in banana leaf and buried in an underground oven) that is utterly authentic." },
  { name: "Mandarin (Fujianese)", community: "Flushing — the Fujianese dialect community, distinct from Mandarin", emoji: "🇨🇳", script: "闽南话", fun_fact: "Fujianese immigrants dominate NYC's Chinatowns — in Flushing, their oyster vermicelli, wonton soup, and Buddha Jumps Over the Wall (a luxury seafood stew so fragrant that even vegetarian monks supposedly leap the monastery wall to eat it) have a devoted following." },
  { name: "Shanghainese", community: "Flushing — Wu Chinese speakers from Shanghai", emoji: "🇨🇳", script: "上海话", fun_fact: "Shanghainese (Wu Chinese) is mutually unintelligible with Mandarin — Shanghainese-owned restaurants in Flushing are celebrated for xiaolongbao (soup dumplings requiring a precise 18-pleat fold) and hong shao rou (Mao Zedong's famously beloved red-braised pork belly)." },
  { name: "Hakka", community: "Flushing & Elmhurst — Hakka Chinese diaspora", emoji: "🇨🇳", script: "客家話", fun_fact: "Hakka people are known as the 'wanderers' of China for their migration history spanning 1,700 years — their salt-baked chicken (cooked in a crust of heated salt to lock in moisture) and pork belly with preserved mustard greens are Hakka cuisine highlights found in Flushing." },
  { name: "Teochew", community: "Flushing — Chaoshan Chinese community", emoji: "🇨🇳", script: "潮州話", fun_fact: "Teochew speakers dominate much of Southeast Asian Chinese diaspora culture — their clear broth soups, oyster omelettes, and chaozhou-style congee (cooked to a silky liquid, topped with dozens of condiments) are quiet stars of Flushing's food scene." },
  { name: "Sinhala", community: "Woodside & Elmhurst — Sri Lankan Tamil and Sinhala community", emoji: "🇱🇰", script: "සිංහල", fun_fact: "Sri Lanka was the world's first country to elect a female prime minister in 1960 — the Sri Lankan community in Queens serves kottu roti (chopped flatbread stir-fry that you hear being made from a block away) and celebrates Vesak (Buddha's birthday) with paper lanterns." },
  { name: "Dhivehi", community: "Flushing — small Maldivian community", emoji: "🇲🇻", script: "ދިވެހި", fun_fact: "The Maldives is the world's lowest-lying country — most of it sits just 1.5 meters above sea level and faces existential threat from rising seas. The tiny Maldivian community in Flushing is one of the most globally unique diaspora groups in all of Queens." },
  { name: "Tok Pisin", community: "Queens — Papua New Guinean community", emoji: "🇵🇬", script: "Tok Pisin", fun_fact: "Papua New Guinea has over 800 languages — more than any other country on Earth (about 12% of all human languages). Tok Pisin is the creole that unites them, and Queens' PNG community brings this extraordinary linguistic diversity to NYC." },
  { name: "Fijian", community: "Queens — Pacific Islander Fijian diaspora", emoji: "🇫🇯", script: "Vosa Vakaviti", fun_fact: "Fiji is world-famous for its rugby sevens team — they won gold at the 2016 and 2020 Olympics, Fiji's only Olympic golds. Queens' Fijian community gathers passionately to watch Sevens tournaments and serves kokoda (Fijian ceviche in coconut cream) at celebrations." },
  { name: "Samoan", community: "Queens — Pacific Islander Samoan community", emoji: "🇼🇸", script: "Gagana Samoa", fun_fact: "Samoa produces more NFL players per capita than any other place on Earth — the Samoan community in Queens hosts White Sunday church celebrations and shares umu (earth oven feast) traditions that bring entire communities together around food." },
  { name: "Tongan", community: "Queens — Pacific Islander Tongan community", emoji: "🇹🇴", script: "lea faka-Tonga", fun_fact: "Tonga is the only Pacific nation that was never fully colonized — the Tongan community in Queens celebrates the king's birthday and church events with otai (fruit drink) and umu feasts, and Tongan churches are known for their extraordinary choral singing." },
  { name: "Hawaiian Pidgin", community: "Queens — Hawaiian diaspora community", emoji: "🌺", script: "Pidgin", fun_fact: "Hawaiian Pidgin (Hawai'i Creole English) developed from plantation worker communities of the 19th century — the Queens Hawaiian diaspora bonds over plate lunches (rice, mac salad, and protein on a paper plate) and aloha spirit in a borough that embodies it." },
  { name: "Ladino", community: "Forest Hills — Sephardic Jewish community with Iberian roots", emoji: "✡️", script: "Judeo-Español", fun_fact: "Ladino is a 500-year-old Spanish-Hebrew hybrid spoken by Sephardic Jews expelled from Spain in 1492 — Forest Hills' Sephardic community preserves it through music, bourekas (flaky savory pastries), and family stories passed down across five centuries of wandering." },
  { name: "Aramaic", community: "Forest Hills & Rego Park — Assyrian and Chaldean Christian community", emoji: "🌐", script: "ܐܪܡܝܐ", fun_fact: "Aramaic was the language of Jesus and the dominant tongue of the ancient Middle East — it's still spoken as a living language by Assyrian and Chaldean Christians in Forest Hills and Rego Park, one of the rarest linguistic survivals anywhere in the world." },
  { name: "Assyrian Neo-Aramaic", community: "Woodside & Forest Hills — Assyrian diaspora community", emoji: "🌐", script: "ܣܘܪܝܬ", fun_fact: "Assyrians are one of the world's oldest continuous civilizations, descended from ancient Mesopotamia — Queens' Assyrian community holds cultural nights featuring zurna (oboe-like instrument) music and kibbeh (bulgur and meat dumplings that date back to ancient recipes)." },
  { name: "Kurdish (Kurmanji)", community: "Astoria & Ridgewood — Kurdish diaspora community", emoji: "🌐", script: "Kurdî", fun_fact: "Kurdish is spoken across Turkey, Syria, Iraq, and Iran but has no single national home — Queens' Kurdish community organizes Newroz (New Year) fire-jumping festivals and serves klecha (cardamom-date cookies) that are among the most fragrant pastries in the borough." },
  { name: "Kurdish (Sorani)", community: "Flushing — Iraqi Kurdish community", emoji: "🌐", script: "کوردی", fun_fact: "Sorani Kurds from Iraqi Kurdistan have built strong communities in Queens — their dolma (grape leaves stuffed with rice, herbs, and pomegranate), kubba soup, and masgouf (whole grilled carp from the Tigris river, Iraq's national dish) are gaining NYC fans." },
  { name: "Romani", community: "Woodside & Astoria — Romani community in Queens", emoji: "🌐", script: "Romani", fun_fact: "Romani people originated in Northwest India and reached Europe over 600 years ago, carrying music traditions that influenced flamenco, jazz, and classical violin — Queens has a Romani community that keeps cimbál (hammered dulcimer) and brass band traditions alive." },
  { name: "Chamorro", community: "Queens — Guamanian and CNMI Pacific Islander community", emoji: "🇬🇺", script: "Chamoru", fun_fact: "Chamorro is one of the most endangered Austronesian languages, now being actively revitalized — Queens' Guamanian community serves red rice (colored with achote seeds) and kelaguen (citrus-marinated meat, Guam's beloved party dish) at festive fiestas." },
  { name: "Palauan", community: "Queens — Micronesian Pacific Islander community", emoji: "🇵🇼", script: "Tekoi ra Belau", fun_fact: "Palau is home to the world's only jellyfish lake where you can swim harmlessly among millions of golden jellyfish — Queens' small Palauan community is one of the rarest Pacific Island diaspora groups in all of NYC." },
  { name: "Marshallese", community: "Queens — Pacific Islander Marshallese community", emoji: "🇲🇭", script: "Kajin M̧ajeļ", fun_fact: "The Marshall Islands face existential threat from rising sea levels (average elevation: 2 meters) — Queens' Marshallese community holds climate awareness events and fundraisers while sharing their sticky rice and breadfruit dishes at community gatherings." },
  { name: "Chuukese", community: "Queens — Micronesian community from Chuuk, Federated States of Micronesia", emoji: "🇫🇲", script: "Chuukese", fun_fact: "Chuuk Lagoon is considered the world's best wreck diving destination, with 60+ WWII Japanese ships sunk in a single US Navy raid in 1944 — Queens' Chuukese community maintains traditional navigation knowledge passed down across generations." },
  { name: "Tigrinya (Eritrean)", community: "Jamaica — Eritrean community distinct from Ethiopian Tigrinya speakers", emoji: "🇪🇷", script: "ትግርኛ", fun_fact: "Eritrea won independence in 1993 after one of Africa's longest liberation struggles (30 years) — Queens' Eritrean community celebrates independence day on May 24 with injera feasts, traditional zufan dance, and extraordinary community solidarity." },
  { name: "Afar", community: "Jamaica & Southeast Queens — Ethiopian and Djiboutian Afar diaspora", emoji: "🇪🇹", script: "Qafar af", fun_fact: "The Afar region in Ethiopia is where Lucy, the 3.2-million-year-old hominid ancestor, was discovered in 1974 — Queens' Afar community carries one of humanity's oldest cultural roots to one of its most diverse neighborhoods." },
  { name: "Sidama", community: "Southeast Queens — Ethiopian Sidama community", emoji: "🇪🇹", script: "Sidaamu Afo", fun_fact: "The Sidama region of Ethiopia is world-renowned for Yirgacheffe coffee — considered among the finest specialty coffees on Earth, with flavors of jasmine and blueberry. Queens' Sidama community takes enormous pride in this coffee legacy." },
  { name: "Hadiyya", community: "Southeast Queens — Ethiopian Hadiyya diaspora", emoji: "🇪🇹", script: "Hadiyyisa", fun_fact: "The Hadiyya people are known for colorful woven textiles and rich oral tradition — Queens' Ethiopian community gatherings often feature handwoven scarves and traditional chano dances that bring multiple generations together." },
  { name: "Luo", community: "Jamaica — Kenyan and Ugandan Luo community", emoji: "🇰🇪", script: "Dholuo", fun_fact: "Barack Obama's father was Luo from Kenya — Queens' Luo community celebrates Luo Cultural Day with nyoyo (boiled maize and beans with coconut) and nyatiti (eight-string lyre) performances that connect the diaspora to home." },
  { name: "Luganda", community: "Southeast Queens — Ugandan Ganda community", emoji: "🇺🇬", script: "Oluganda", fun_fact: "Luganda is the language of Uganda's Buganda kingdom, one of Africa's most sophisticated pre-colonial civilizations — Queens' Ugandan community serves rolex (chapati rolled around fried eggs, Uganda's beloved street food) and matoke (steamed green banana stew)." },
  { name: "Kinyarwanda", community: "Southeast Queens — Rwandan community", emoji: "🇷🇼", script: "Kinyarwanda", fun_fact: "Rwanda transformed from tragedy to one of Africa's fastest-growing economies in 30 years, and became the first country with a female parliamentary majority — Queens' Rwandan community celebrates this resilience with isombe (cassava leaves with peanut sauce) at community dinners." },
  { name: "Kirundi", community: "Southeast Queens — Burundian community", emoji: "🇧🇮", script: "Ikirundi", fun_fact: "Burundian drumming (karyenda) is a UNESCO Intangible Cultural Heritage — the Burundian community in Queens performs traditional ingoma drum ceremonies at cultural events that leave audiences in awe of this ancient percussion tradition." },
  { name: "Chichewa", community: "Southeast Queens — Malawian community", emoji: "🇲🇼", script: "Chichewa", fun_fact: "Malawi is called 'the warm heart of Africa' for the friendliness of its people — Queens' Malawian community serves nsima (thick cornmeal porridge eaten by hand, formed into a ball and dipped into relish) at community gatherings that embody that welcoming spirit." },
  { name: "Ndebele", community: "Southeast Queens — Zimbabwean Ndebele community", emoji: "🇿🇼", script: "isiNdebele", fun_fact: "Ndebele women are famous worldwide for their striking geometric body painting and beadwork, featured in museums from Paris to New York — Queens' Zimbabwean Ndebele community has displayed this vibrant art at cultural festivals in the borough." },
  { name: "Sesotho", community: "Southeast Queens — Lesotho and South African Sotho diaspora", emoji: "🇱🇸", script: "Sesotho", fun_fact: "Lesotho is entirely surrounded by South Africa — it is one of only three countries in the world entirely enclosed within another nation (Vatican and San Marino are the others). Queens' Basotho community keeps mokhibo (a traditional dance on bent knees) alive." },
  { name: "Setswana", community: "Southeast Queens — Botswanan and South African community", emoji: "🇧🇼", script: "Setswana", fun_fact: "Botswana has one of Africa's strongest democracies and went from the world's poorest country in 1966 to upper-middle income today — Queens' Tswana community is known for Setswana music gatherings and seswaa (pounded beef stew, the national dish)." },
  { name: "Fante", community: "Southeast Queens — Ghanaian Fante coastal community", emoji: "🇬🇭", script: "Mfantse", fun_fact: "Fante people from Ghana's Cape Coast were key figures in the era of Atlantic trade — their etsew (palm nut soup with crab) and fante fante (fresh fish stew) are coastal Ghanaian delicacies that can be found at Queens community gatherings." },
  { name: "Nuer", community: "Jamaica — South Sudanese Nuer refugee community", emoji: "🇸🇸", script: "Thok Nath", fun_fact: "The Nuer are known for their age-set initiation scars (gaar) — many South Sudanese in Queens are former 'Lost Boys' who walked hundreds of miles as children to survive the civil war, then rebuilt their lives entirely in Queens. Among the most remarkable stories in the borough." },
  { name: "Zarma", community: "Southeast Queens — Nigerien Zarma community", emoji: "🇳🇪", script: "Zarma", fun_fact: "The Zarma are descended from the Songhai Empire, once the largest empire in West African history spanning the entire Niger River bend — their tuwo (millet porridge) and dambou (moringa leaf couscous) are Queens community staples." },
  { name: "Tamasheq", community: "Southeast Queens — Tuareg diaspora from Mali and Niger", emoji: "🌐", script: "ⵍⵎⴰⵙⵚⵉⵔ", fun_fact: "The Tuareg are the legendary 'Blue People of the Sahara' — their indigo robes dye their skin blue over time. Their desert rock music (played on the tehardent lute, famously influenced Santana and Led Zeppelin) and tagella (sand-baked bread) are served at Queens gatherings." },
  { name: "Sango", community: "Southeast Queens — Central African Republic community", emoji: "🇨🇫", script: "Sângbä", fun_fact: "Sango is one of the few African languages that became a national language from a creole pidgin — the Central African community in Queens brings gozo (cassava pudding with peanut sauce) and moambe (palm nut chicken stew) to a borough that loves bold flavors." },
  { name: "Tetum", community: "Queens — Timorese community from East Timor", emoji: "🇹🇱", script: "Tetun", fun_fact: "East Timor (Timor-Leste) only gained independence in 2002 after one of history's longest resistance movements against Indonesian occupation — the small but proud Timorese community in Queens hosts events celebrating their hard-won independence with arroz de cabidela (chicken blood rice)." },
  { name: "Malagasy", community: "Queens — Malagasy community from Madagascar", emoji: "🇲🇬", script: "Malagasy", fun_fact: "Madagascar split from mainland Africa 88 million years ago and has thousands of species found nowhere else — 95% of its reptiles, 89% of plants, and all its lemurs are endemic. Queens' Malagasy community serves romazava (beef and greens stew) and ravitoto (pork with cassava leaves)." },
  { name: "Mauritian Creole", community: "Queens — Mauritian community", emoji: "🇲🇺", script: "Kreol Morisyen", fun_fact: "Mauritius is where the dodo bird lived until its extinction in the 1690s — and Queens' Mauritian community brings one of the world's most diverse cuisines (Indian, Chinese, African, and French all genuinely fused over centuries) to a borough that appreciates fusion done right." },
  { name: "Seychellois Creole", community: "Queens — Seychellois diaspora", emoji: "🇸🇨", script: "Kreol seselwa", fun_fact: "The Seychelles has the world's largest coco de mer palms (seeds weighing up to 25kg, shaped remarkably like a human bottom) — Queens' small Seychellois community is one of the rarest island diaspora groups anywhere in NYC, known for ladob (sweet banana and breadfruit pudding)." },
  { name: "Cape Verdean Creole", community: "Queens — Cape Verdean community", emoji: "🇨🇻", script: "Kriolu", fun_fact: "Cape Verde produced Cesária Évora, 'the Barefoot Diva,' whose morna (melancholic folk music embodying saudade) won a Grammy — Queens' Cape Verdean community gathers for live morna performances and cachupa (slow-cooked bean and corn stew, the national dish)." },
  { name: "São Toméan Creole", community: "Queens — São Tomé and Príncipe community", emoji: "🇸🇹", script: "Forro", fun_fact: "São Tomé and Príncipe straddles the equator in the Gulf of Guinea and was uninhabited until the Portuguese arrived in 1470 — Queens' community from this island nation is extraordinarily rare in NYC, making it one of the most unique diaspora communities in the entire borough." },
  { name: "Dzongkha", community: "Woodside — Bhutanese refugee community resettled in Queens", emoji: "🇧🇹", script: "རྫོང་ཁ", fun_fact: "Bhutan is the only carbon-negative country in the world and still measures Gross National Happiness instead of GDP — Queens' Bhutanese refugees (many resettled from Nepali camps over 15+ years) bring momos, ema datshi (chili cheese stew, the national dish), and that philosophy of collective well-being to the borough." },
];

export default function QueensTranslator() {
  const [tagline, setTagline] = useState("");
  const [language, setLanguage] = useState(null);
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [tried, setTried] = useState(false);

  const pickRandomLanguage = () => {
    const idx = Math.floor(Math.random() * QUEENS_LANGUAGES.length);
    return QUEENS_LANGUAGES[idx];
  };

  const translate = async () => {
    if (!tagline.trim()) return;
    setLoading(true);
    setResult(null);
    const lang = pickRandomLanguage();
    setLanguage(lang);
    setTried(true);

    const response = await base44.integrations.Core.InvokeLLM({
      prompt: `You are a fun, enthusiastic translator for a marketing keynote event in Queens, NY — the most linguistically diverse place on Earth.

Translate this startup marketing tagline into ${lang.name}:
"${tagline}"

Return ONLY this JSON (no extra text):
{
  "translation": "the translated text",
  "pronunciation": "phonetic pronunciation guide for English speakers (romanized, easy to read)",
  "literal_meaning": "a fun note about what it literally means or any interesting nuance",
  "marketing_insight": "one sentence about how ${lang.name}-speaking communities in Queens might uniquely respond to this message — tie it to marketing"
}`,
      response_json_schema: {
        type: "object",
        properties: {
          translation: { type: "string" },
          pronunciation: { type: "string" },
          literal_meaning: { type: "string" },
          marketing_insight: { type: "string" },
        },
      },
    });

    setResult(response);
    setLoading(false);
  };

  return (
    <div className="bg-gradient-to-br from-purple-900 via-blue-900 to-indigo-900 rounded-3xl p-8 md:p-10 overflow-hidden relative">
      <div className="absolute inset-0 opacity-10">
        <div className="absolute top-4 left-8 text-6xl">🌍</div>
        <div className="absolute top-8 right-12 text-5xl">🗽</div>
        <div className="absolute bottom-8 left-16 text-4xl">🌏</div>
        <div className="absolute bottom-4 right-8 text-5xl">🌎</div>
      </div>

      <div className="relative z-10">
        <div className="text-center mb-8">
          <div className="inline-flex items-center gap-2 bg-yellow-400 text-yellow-900 text-xs font-bold px-3 py-1.5 rounded-full mb-4">
            <Globe className="w-3.5 h-3.5" /> QUEENS EXCLUSIVE EXPERIENCE
          </div>
          <h3 className="text-2xl md:text-3xl font-bold text-white mb-2">
            The Queens Language Challenge 🗺️
          </h3>
          <p className="text-blue-200 text-sm max-w-xl mx-auto leading-relaxed">
            Queens is the most linguistically diverse place on Earth — <strong className="text-white">160+ languages</strong> spoken across 2.3 million people.
            Type your startup tagline and discover how it sounds in a random Queens language.
          </p>
          <p className="text-white/40 text-xs mt-2">160 languages in this experience — matching Queens' real diversity</p>
        </div>

        <div className="max-w-xl mx-auto mb-6">
          <label className="block text-blue-200 text-sm font-semibold mb-2">Your startup tagline or marketing message:</label>
          <div className="flex gap-2">
            <input
              value={tagline}
              onChange={(e) => setTagline(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && !loading && translate()}
              placeholder="e.g. The fastest way to find your first customers"
              className="flex-1 bg-white/10 border border-white/20 text-white placeholder-white/40 rounded-xl px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-yellow-400 focus:border-transparent"
            />
            <button
              onClick={translate}
              disabled={loading || !tagline.trim()}
              className="px-5 py-3 bg-yellow-400 text-yellow-900 font-bold rounded-xl hover:bg-yellow-300 transition-colors disabled:opacity-40 flex items-center gap-2 whitespace-nowrap text-sm"
            >
              {loading ? (
                <RefreshCw className="w-4 h-4 animate-spin" />
              ) : (
                <><Sparkles className="w-4 h-4" /> Translate!</>
              )}
            </button>
          </div>
        </div>

        {loading && (
          <div className="text-center py-8">
            <Globe className="w-10 h-10 text-yellow-400 mx-auto mb-3 animate-pulse" />
            <p className="text-blue-200 text-sm">Picking a random Queens language and translating…</p>
          </div>
        )}

        <AnimatePresence>
          {result && language && !loading && (
            <motion.div
              initial={{ opacity: 0, y: 20, scale: 0.95 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.4 }}
              className="max-w-2xl mx-auto"
            >
              <div className="bg-white/10 backdrop-blur border border-white/20 rounded-2xl p-6">
                <div className="flex items-center gap-3 mb-5 pb-4 border-b border-white/20">
                  <span className="text-4xl">{language.emoji}</span>
                  <div>
                    <div className="flex items-center gap-2">
                      <h4 className="text-xl font-bold text-white">{language.name}</h4>
                      <span className="text-white/50 text-sm">{language.script}</span>
                    </div>
                    <p className="text-blue-300 text-xs mt-0.5">📍 {language.community}</p>
                  </div>
                </div>

                <div className="mb-4">
                  <p className="text-xs font-semibold text-yellow-400 uppercase tracking-widest mb-1">Your tagline in {language.name}:</p>
                  <p className="text-2xl font-bold text-white leading-relaxed">{result.translation}</p>
                </div>

                <div className="bg-white/10 rounded-xl p-4 mb-4">
                  <div className="flex items-center gap-1.5 mb-1">
                    <Volume2 className="w-3.5 h-3.5 text-blue-300" />
                    <p className="text-xs font-semibold text-blue-300 uppercase tracking-widest">How to say it:</p>
                  </div>
                  <p className="text-white text-sm font-mono">{result.pronunciation}</p>
                </div>

                {language.fun_fact && (
                  <div className="bg-orange-400/10 border border-orange-400/20 rounded-xl p-4 mb-4">
                    <p className="text-xs font-semibold text-orange-300 mb-1">🌟 Fun fact:</p>
                    <p className="text-orange-100 text-sm leading-relaxed">{language.fun_fact}</p>
                  </div>
                )}

                <div className="grid sm:grid-cols-2 gap-3">
                  {result.literal_meaning && (
                    <div className="bg-yellow-400/10 border border-yellow-400/20 rounded-xl p-4">
                      <p className="text-xs font-semibold text-yellow-400 mb-1">🔤 Nuance:</p>
                      <p className="text-yellow-100 text-sm leading-relaxed">{result.literal_meaning}</p>
                    </div>
                  )}
                  {result.marketing_insight && (
                    <div className="bg-green-400/10 border border-green-400/20 rounded-xl p-4">
                      <p className="text-xs font-semibold text-green-400 mb-1">📈 Marketing insight:</p>
                      <p className="text-green-100 text-sm leading-relaxed">{result.marketing_insight}</p>
                    </div>
                  )}
                </div>

                <div className="mt-5 text-center">
                  <button
                    onClick={translate}
                    className="inline-flex items-center gap-2 px-5 py-2.5 bg-white/10 border border-white/20 text-white text-sm font-semibold rounded-xl hover:bg-white/20 transition-colors"
                  >
                    <Shuffle className="w-4 h-4" /> Translate into a different Queens language
                  </button>
                </div>
              </div>

              <p className="text-center text-white/30 text-xs mt-3">
                This is one of 160 languages in this experience — Queens has 160+ total. Reach them all with the right marketing.
              </p>
            </motion.div>
          )}
        </AnimatePresence>

        {!tried && !loading && (
          <div className="text-center">
            <p className="text-white/40 text-xs">↑ Try it — every translation is a surprise from a real Queens community</p>
          </div>
        )}
      </div>
    </div>
  );
}